# Site settings
title: Portál otevřených dat České republiky

description: Portál otevřených dat a Národní katalog otevřených dat České republiky
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://data.gov.cz" # the base hostname & protocol for your site
#develop: true

# Build settings
excerpt_separator: <!--more-->

timezone: Europe/Prague
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

langs:
  en:
    cs: česky
    flag: /images/flag-en.svg
  cs:
    en: English
    flag: /images/flag-cs.svg

collections:
  clanky:
    output: true
    permalink: /články/:path
